apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blog.fullname" . }}-config
  labels:
    {{- include "blog.labels" . | nindent 4 }}
data:
  {{- $cfg := index .Values.configuration .Release.Namespace }}
  HUGO_BASEURL: "{{ $cfg.HUGO_BASEURL }}"