name: Content Suggestion
description: Suggest a topic or idea for new blog content
title: "[Content Suggestion]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting new content! Please describe your idea below.

  - type: textarea
    id: content_idea
    attributes:
      label: Content Idea
      description: Describe your idea for new blog content.
      placeholder: I have an idea for a post about...
    validations:
      required: true
