name: Broken link check
on: 
  schedule:
  - cron: "0 * * * *"
  push:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Broken Link Checker Action
      uses: technote-space/broken-link-checker-action@v1.1.3
      with:
        TARGET: 'https://www.funkysi1701.com' 
        EXCLUDED_KEYWORDS: linkedin.com,twitter.com,t.co
        RECURSIVE: true
