name: Broken link check
on: 
  schedule:
  - cron: "0 4 * * *"
  push:
jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Broken Link Checker Action
      uses: technote-space/broken-link-checker-action@v2.3.1
      with:
        TARGET: 'https://www.funkysi1701.com,https://www.funkysi1701.com/posts/about/,https://www.funkysi1701.com/posts/pwned-pass/,https://www.funkysi1701.com/posts/,https://www.funkysi1701.com/posts/2022/diagrams-with-mermaid/ ' 
        RECURSIVE: false
