name: Local Deployment

on:
  workflow_dispatch:
  push:
jobs:
  build_and_deploy_locally:
    runs-on: self-hosted
    name: Build and Deploy Locally
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Git checkout
        uses: actions/checkout@v4
      - name: stop Hugo
        continue-on-error: true
        run: docker stop hugo                  
      - name: hugo
        run: docker run --name hugo -d --rm -v .:/src -p 1313:1313 floryn90/hugo:0.119.0 server -D --config config-dev.toml --buildFuture --baseURL="http://server05.local:1313/"
